CREATE SCHEMA IF NOT EXISTS ecommerce;

CREATE TABLE ecommerce.customer (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(255),
                                    email VARCHAR(255),
                                    mobile VARCHAR(20),
                                    delivery_address VARCHAR(500)
);